---
- name: "Install and configure database for CMF on Windows"
  hosts: windows
  become: false
  gather_facts: true
  vars_files:
    - ../values.yml
    - ../secrets.yml
  tasks:
    - name: Change the hostname to 
      ansible.windows.win_hostname:
        name: "{{ cmf_db_server_name }}"
      register: res

    - name: Reboot if required
      ansible.windows.win_reboot:
      when: res.reboot_required

    - name: create user account for db on windows
      # Content suggestion provided by Ansible Lightspeed
      ansible.windows.win_user:
        name: "{{ db_username }}"
        password: "{{ db_password }}"
        groups:
          - Users
        state: present
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: 'C:\temp\'
        state: directory
        mode: '0755'
      register: _outputDir
    
    - name: Populate the SQL server templates
      ansible.builtin.template:
        src: ../templates/dbconfigfile.ini.j2
        dest: 'C:\temp\Configfile.ini'

    # - name: Install SQL server on windows
    #   # Content suggestion provided by Ansible Lightspeed
    #   ansible.windows.win_package:
    #     path: "https://download.microsoft.com/download/4/1/b/41b9a8c3-c2b4-4fcc-a3d5-62feed9e6885/SQL2022-SSEI-Eval.exe?culture=en-us&country=us"
    #     # product_id: "{{ _product_id_ }}"
    #     arguments: |
    #       "/Q 
    #       /IACCEPTSQLSERVERLICENSETERMS 
    #       /ACTION='install'
    #       /PID="AAAAA-BBBBB-CCCCC-DDDDD-EEEEE" 
    #       /FEATURES=SQL,AS,IS
    #       /INSTANCENAME=ONLINE 
    #       /SQLSVCACCOUNT="\MyAccount"
    #       /SQLSVCPASSWORD="************" 
    #       /SQLSYSADMINACCOUNTS="localhost\"
    #       /AGTSVCACCOUNT="\cmfsu" 
    #       /AGTSVCPASSWORD="************"
    #       /ASSVCACCOUNT="MyDomain\MyAccount" 
    #       /ASSVCPASSWORD="************"
    #       /ISSVCACCOUNT="MyDomain\MyAccount" 
    #       /ISSVCPASSWORD="************"
    #       /ASSYSADMINACCOUNTS="MyDomain\MyAccount"
  # collation Latin1_General_CI_AS

    #   register: sql_server_install_result
    #   failed_when: sql_server_install_result.rc != 0
    #   changed_when: sql_server_install_result.rc == 0

#  STEPS TO DO
    # Create cmfsu user
    # install sql server https://download.microsoft.com/download/4/1/b/41b9a8c3-c2b4-4fcc-a3d5-62feed9e6885/SQL2022-SSEI-Eval.exe?culture=en-us&country=us
    # install SSRS https://download.microsoft.com/download/1/a/a/1aaa9177-3578-4931-b8f3-373b24f63342/SQLServerReportingServices.exe
    # alter ssrs config to allow user login
    # mount installation data directory - MOUNT AS SATA!!!!
    # fix SQL server instance ports

# ------ scripts to run on windows to enable Ansible. Build into golden image -----
# Get-NetConnectionProfile | Set-NetConnectionProfile -NetworkCategory Private
# Enable-PSRemoting -Force
# winrm quickconfig -q
# winrm quickconfig -transport:http
# winrm set winrm/config '@{MaxTimeoutms="1800000"}'
# winrm set winrm/config/winrs '@{MaxMemoryPerShellMB="800"}'
# winrm set winrm/config/service '@{AllowUnencrypted="true"}'
# winrm set winrm/config/service/auth '@{Basic="true"}'
# winrm set winrm/config/client/auth '@{Basic="true"}'
# winrm set winrm/config/listener?Address=*+Transport=HTTP '@{Port="5985"}'
# netsh advfirewall firewall set rule group="Windows Remote Administration" new enable=yes
# netsh advfirewall firewall set rule name="Windows Remote Management (HTTP-In)" new enable=yes action=allow remoteip=any
# Set-Service winrm -startuptype "auto"
# Restart-Service winrm
    
